name: Pull Request Checker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate annotation
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          path: annotation
          skip_sarif: true

      - name: Validate annotation
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          path: codegen
          skip_sarif: true

      - name: Validate annotation
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          generate_code: true
          path: json_theme
          
